# Generated by Django 4.2.4 on 2023-10-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0018_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
