# Generated by Django 4.2.4 on 2023-10-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0023_remove_post_img_remove_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
    ]
