# Generated by Django 4.2.4 on 2023-09-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
