# Generated by Django 4.2.4 on 2023-10-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_profile_fb_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/social/'),
        ),
    ]
