# Generated by Django 4.2.4 on 2023-10-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_profile_facebook_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/social/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/social/'),
        ),
    ]
